import { randomUUID } from 'crypto';
import { Request, Response } from 'express';
import { config } from '../../config';
import { db } from '../../config/database';
import { createUploadPost } from '../../services/s3.service';
import {
  AllowedContentType,
  AssetIdParams,
  CreateAssetInput,
  EXTENSION_BY_CONTENT_TYPE,
  ListAssetsQuery,
} from './schema';

// Keys are generated by the server from UUIDs, but encode each segment anyway so a legacy key
// (which contains the user's filename) can never produce a broken or ambiguous URL.
const buildCdnUrl = (key: string | null): string | null =>
  key
    ? `https://${config.aws.cloudfront.domainName}/${key.split('/').map(encodeURIComponent).join('/')}`
    : null;

export const createAssetHandler = async (req: Request<{}, {}, CreateAssetInput>, res: Response) => {
  const { filename, fileSizeBytes, contentType } = req.body;

  const assetId = randomUUID();
  const s3Key = `originals/${assetId}/original.${EXTENSION_BY_CONTENT_TYPE[contentType as AllowedContentType]}`;

  // Sign first: it has no side effects, so a failure here cannot leave an orphaned row behind.
  const upload = await createUploadPost(s3Key, contentType);

  await db.none(
    'INSERT INTO assets (id, original_filename, content_type, size_bytes, original_s3_key) \
    VALUES ($1, $2, $3, $4, $5)',
    [assetId, filename, contentType, fileSizeBytes, s3Key]
  );

  res.status(201).json({ assetId, upload });
};

export const getAssetsHandler = async (_req: Request, res: Response) => {
  const { limit, offset } = res.locals.validated.query as ListAssetsQuery;

  const [rows, { count }] = await Promise.all([
    db.any(
      `SELECT a.id, a.original_filename, a.content_type, a.size_bytes, a.status,
              a.original_s3_key, a.created_at, a.updated_at,
              (SELECT v.s3_key FROM variants v WHERE v.asset_id = a.id
                ORDER BY v.width::bigint * v.height ASC LIMIT 1) AS thumbnail_s3_key
         FROM assets a
        WHERE a.status <> 'deleting'
        ORDER BY a.created_at DESC
        LIMIT $1 OFFSET $2`,
      [limit, offset]
    ),
    db.one("SELECT count(*)::int AS count FROM assets WHERE status <> 'deleting'"),
  ]);

  const items = rows.map(({ original_s3_key, thumbnail_s3_key, ...asset }) => ({
    ...asset,
    url: buildCdnUrl(original_s3_key),
    thumbnail_url: buildCdnUrl(thumbnail_s3_key),
  }));

  res.status(200).json({ items, total: count, limit, offset });
};

export const getAssetHandler = async (req: Request<AssetIdParams>, res: Response) => {
  const { assetId } = req.params;

  // db.one rejects with QueryResultError when no row matches; the error handler maps that to 404
  const asset = await db.one("SELECT * FROM assets WHERE id = $1 AND status <> 'deleting'", assetId);
  const variants = await db.any(
    `SELECT
      v.id, v.s3_key, v.width, v.height, v.content_type, v.size_bytes, v.created_at,
      p.name, p.format, p.quality
    FROM variants v
    LEFT JOIN presets p ON v.preset_id = p.id
    WHERE v.asset_id = $1
    ORDER BY v.width::bigint * v.height ASC`,
    assetId
  );

  res.status(200).json({
    ...asset,
    url: buildCdnUrl(asset.original_s3_key),
    variants: variants.map(variant => ({ ...variant, url: buildCdnUrl(variant.s3_key) })),
  });
};
